# Generated by Django 4.2.2 on 2023-07-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_student_courses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
