# Generated by Django 4.2.2 on 2023-07-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(default='3 Months', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='fees',
            field=models.CharField(default='1000', max_length=100000),
        ),
    ]
